ArtStore.Web/Controllers/ArtController.cs
using ArtStore.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArtStore.Web.Controllers
{
    public class ArtController : Controller
    {
        private IArtServices _artServices;

        public ArtController(IArtServices artServices)
        {
            _artServices = artServices;
        }
        public ActionResult AllProduct(string search)
        {
            
            var arts = _artServices.GetAll();
            if (!String.IsNullOrEmpty(search))
            {
                arts=arts.Where(s=>s.Name.Contains(search));
            }
            return View(arts);
        }
        // GET: Art
        public ActionResult Details(int artId)
        {
            var art = _artServices.GetById(artId);
            if (art == null)
            {
                return HttpNotFound();
            }
            return View(art);
        }
      

    }
}

ArtStore.Web/Controllers/CartController.cs
using ArtStore.Services;
using ArtStore.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArtStore.Web.Controllers
{
    public class CartController : Controller
    {
        private readonly IArtServices _artServices;

        public CartController(IArtServices artServices)
        {
            _artServices = artServices;
        }

        // GET: Cart
        public ActionResult Index()
        {
            var cart = Session["cart"] as List<CartItemViewModel> ?? new List<CartItemViewModel>();

            if (cart.Count == 0 || Session["cart"] == null)
            {
                ViewBag.Message = "There are no items in your bag.";
                return View();
            }

            decimal totalPrice = 0m;

            foreach (var item in cart)
            {
                totalPrice += item.Price * item.Quantity;
            }

            ViewBag.TotalPrice = totalPrice;

            return View(cart);
        }

        public int CartNoti()
        {
            var cart = Session["cart"] as List<CartItemViewModel> ?? new List<CartItemViewModel>();

            return cart.Count;
        }

        public ActionResult AddToCart(int artId)
        {
            var art = _artServices.GetById(artId);
            if (art == null)
            {
                return HttpNotFound();
            }
            List<CartItemViewModel> cart = (List<CartItemViewModel>)Session["cart"];
            if (cart == null)
            {
                cart = new List<CartItemViewModel>();
            }
            foreach (var cartItem in cart)
            {
                if (cartItem.Art.Id == artId)
                {
                    cartItem.Quantity++;
                    Session["cart"] = cart;
                    return RedirectToAction("Index", "Home");
                }
            }
            CartItemViewModel item = new CartItemViewModel()
            {
                Art = art,
                Quantity = 1,
                Price = art.Price
            };
            cart.Add(item);

            Session["cart"] = cart;
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Increment(int itemIndex)
        {
            List<CartItemViewModel> cart = (List<CartItemViewModel>)Session["cart"];
            cart.ElementAt(itemIndex).Quantity++;
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
        //GET: Cart/Decrement/itemIndex
        public ActionResult Decrement(int itemIndex)
        {
            List<CartItemViewModel> cart = (List<CartItemViewModel>)Session["cart"];
            if (cart.ElementAt(itemIndex).Quantity == 1)
            {
                return RemoveItem(itemIndex);
            }
            else
            {
                cart.ElementAt(itemIndex).Quantity--;
            }
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
        //GET: Cart/RemoveItem/itemIndex
        public ActionResult RemoveItem(int itemIndex)
        {
            List<CartItemViewModel> cart = (List<CartItemViewModel>)Session["cart"];
            cart.RemoveAt(itemIndex);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
    }
}

ArtStore.Web/Controllers/CategoryController.cs
using ArtStore.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArtStore.Web.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryServices _categoryServices;
        private IArtServices _artServices;

        public CategoryController(ICategoryServices categoryServices, IArtServices artServices)
        {
            _categoryServices = categoryServices;
            _artServices = artServices;
        }

        // GET: Category
        public ActionResult GetAllCategory()
        {
            var categories = _categoryServices.GetAll();
            return PartialView("_ListCategories", categories);
        }
        public ActionResult Details(int cateId)
        {
            var cate = _categoryServices.GetById(cateId);
            if (cate == null)
            {
                return HttpNotFound();
            }
            var arts = _artServices.GetArtByCategory(cate.Id);
            ViewBag.Name = cate.Name;
            return View("_ListArts", arts);
        }
    }
}

ArtStore.Web/Views/Shared/CartNoti.cshtml
            <li class="minicart-wrap">
                <a href="@Url.Action("Index","Cart")" class="minicart-btn toolbar-btn">
                    <i class="fa fa-shopping-cart"></i>
                    <span class="cart-item_count">@Html.Action("CartNoti","Cart")</span>
                </a>
            </li>
            <li class="sidemenu-wrap">
                <a href="#"><i class="fa fa-search"></i> </a>
                <ul class="dropdown-sidemenu dropdown-hover-2 dropdown-search">
                    <li>
                        <form action="#">
                            <input name="search" id="search" placeholder="Search" type="text">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </li>
                </ul>
            </li>
            @Html.Partial("_LoginPartial")
         
            <li class="mobile-menu-btn d-lg-none">
                <a class="off-canvas-btn" href="#">
                    <i class="fa fa-bars"></i>
                </a>
            </li>
 

ArtStore.Web/Views/Shared/_ArtOverview.cshtml
@model Art

<div class="mb-30 col-lg-4">
    <div class="product-i">
        <a class="d-block" href="@Url.Action("Details", "Art", new {artId = Model.Id})">
            <img src="~/assets/images/@Model.Image" class="product-image-1 w-100" alt="...">
        </a>
    </div>

    <div class="product-c">
        <div class="product-t" style="padding:10px;text-align:center">
            <a href="@Url.Action("Details", "Art", new {artId = Model.Id})"><h4 class="class=" title-2"">@Model.Name</h4></a>
        </div>
        <div class="price"style="text-align:center;margin-bottom:10px">
            <b class="r-price ">@(Model.SalePercent > 0 ? (Model.Price - Model.SalePercent * Model.Price/100).ToString("F0"):Model.Price.ToString("F0"))đ</b>
            @if (Model.SalePercent > 0)
            {
                <span class="o-price"><del>@Model.Price.ToString("F0")đ</del></span>
            }
        </div>
        <div style="text-align: center; padding: 10px 20px; color: red ">
            <a style="font-size:15px;line-height:2" href="@Url.Action("AddToCart", "Cart", new {artId = Model.Id})" class="btn flosun-button secondary-btn black-color rounded-0 w-100">Add to cart</a>
        </div>
        
    </div>
</div>

ArtStore.Web/Views/Shared/_Banner.cshtml
<div class="intro11-slider-wrap section">
    <div class="intro11-slider swiper-container">
        <div class="swiper-wrapper">
            <div class="intro11-section swiper-slide slide-1 slide-bg-1 bg-position">
                <!-- Intro Content Start -->
                <div class="intro11-content text-left">

                </div>
                <!-- Intro Content End -->
            </div>
            <div class="intro11-section swiper-slide slide-2 slide-bg-1 bg-position">
                <!-- Intro Content Start -->
                <div class="intro11-content text-left">
                    <h3 class="title-slider black-slider-title text-uppercase">Collection</h3>
                    <h2 class="title">Flowers and Candle <br> Birthday Gift</h2>
                    <p class="desc-content">Lorem ipsum dolor sit amet, pri autem nemore bonorum te. Autem fierent ullamcorper ius no, nec ea quodsi invenire. </p>
                    <a href="product-details.html" class="btn flosun-button secondary-btn rounded-0">Shop Now</a>
                </div>
                <!-- Intro Content End -->
            </div>
        </div>
        <!-- Slider Navigation -->
        <div class="home1-slider-prev swiper-button-prev main-slider-nav"><i class="lnr lnr-arrow-left"></i></div>
        <div class="home1-slider-next swiper-button-next main-slider-nav"><i class="lnr lnr-arrow-right"></i></div>
        <!-- Slider pagination -->
        <div class="swiper-pagination"></div>
    </div>
</div>

ArtStore.Web/Views/Shared/_ListArts.cshtml
@model IEnumerable<Art>
@{
    ViewBag.Title = ViewBag.Name;
}

<div class="container" style="margin-top:100px">
    <h2>@ViewBag.Name</h2>
    <div class="cat-main">
        <li><a href="@Url.Action("AllProduct", "Art", new { area = "" })">All</a></li>
        @Html.Action("GetAllCategory", "Category")

    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            @Html.Partial("_ArtOverview", item)
        }
    </div>
</div>

ArtStore.Web/Views/Shared/_ListCategories.cshtml
@model IEnumerable<Category>

@foreach (var item in Model)
{
    <li>
        <a href="@Url.Action("Details", "Category", new {cateId = item.Id})">
            <span class="menu-text">@item.Name</span>
        </a>
    </li>
}