ArtStore.Web/Areas/Admin/Controllers/OrderManagementController.cs
using ArtStore.Models;
using ArtStore.Services;
using ArtStore.Web.Areas.Admin.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ArtStore.Web.Areas.Admin.Controllers
{
    public class OrderManagementController : Controller
    {
        private readonly IOrderServices _orderServices;
        private readonly IArtServices _artServices;
        private readonly IOrderDetailServices _orderDetailServices;

        public OrderManagementController(IOrderServices orderServices, IArtServices artServices, IOrderDetailServices orderDetailServices)
        {
            _orderServices = orderServices;
            _artServices = artServices;
            _orderDetailServices = orderDetailServices;
        }

        private AccountManager _userManager;
        public AccountManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<AccountManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // GET: Admin/OrderManagement
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string search, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;

            if (search != null)
            {
                pageIndex = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewData["CurrentFilter"] = search;

            Expression<Func<Order, bool>> filter = null;

            if (!String.IsNullOrEmpty(search))
            {
                filter = c => c.Address.Contains(search);
            }

            Func<IQueryable<Order>, IOrderedQueryable<Order>> orderBy = null;

            switch (sortOrder)
            {
                default:
                    orderBy = n => n.OrderByDescending(p => p.Id);
                    break;
            }

            var orders = await _orderServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(orders);
        }

        // GET: Admin/OrderManagement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Order order = _orderServices.GetById((int)id);
            if (order == null)
            {
                return HttpNotFound();
            }

            var orderViewModel = new OrderViewModel
            {
                Id = order.Id,
                Address = order.Address,
                CreateDate = order.CreateDate,
                Status = order.Status,
                TotalPrice = order.TotalPrice,
                CusName = UserManager.FindById(order.AccountId).UserName
            };
            return View(orderViewModel);
        }

        public ActionResult GetOrderDetails(int orderId)
        {
            var list = _orderDetailServices.GetOrderDetailsByOrder(orderId);
            return PartialView("GetOrderDetails", list);
        }

        public string GetAccountName(string accId)
        {
            var user = UserManager.FindById(accId);
            return user.Name;
        }

        public string GetArtName(int artId)
        {
            var name = _artServices.GetById(artId).Name;
            return name;
        }

        // POST: Admin/OrderManagement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(OrderViewModel orderViewModel)
        {
            if (ModelState.IsValid)
            {
                var order = _orderServices.GetById(orderViewModel.Id);
                if(order == null)
                {
                    return HttpNotFound();
                }
                orderViewModel.Address = order.Address;
                
                if(orderViewModel.Status == 0)
                {
                    order.Status = 1;
                }

                var result = _orderServices.Update(order);
                if (result)
                {
                    TempData["Message"] = "Cập nhật thành công.";

                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["Message"] = "Cập nhật thất bại.";
                }
            }
            return View(orderViewModel);
        }
    }
}

ArtStore.Web/Areas/Admin/Views/OrderManagement/Edit.cshtml
@model OrderViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Order</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group col-md-6">
            CustomerName
            <br />
            <br />
            @Html.EditorFor(model => model.CusName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
        <div class="form-group col-md-6">
            Address
            <br />
            <br />
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
        <div class="form-group col-md-6">
            <br />
            OrderDate
            <br />
            <br />
            @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>

        <div class="form-group">
            @Html.Action("GetOrderDetails", "OrderManagement", new { orderId = Model.Id })
        </div>

        <div class="form-group col-md-6">
            <div class="col-md-5">
                <br />
                TotalOrder
                <br />
                @Html.EditorFor(model => model.TotalPrice, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>

        <div class="form-group col-md-6">
            <br />
            @Html.HiddenFor(m => m.Status)
            Status: <b>@(Model.Status == 0 ? "Pending" : "Success")</b>
        </div>

        
        @if (Model.Status == 0)
        {
            <div class="form-group form-button mt-4">
                <input type="submit" name="signup" id="signup" class="btn btn-success" value="Hoàn Thành" />
                @Html.ActionLink("Trở Về", "Index", null, new { @class = "btn btn-light ml-2" })
            </div>
        }
        else
        {
            <div class="form-group form-button mt-4">
                @Html.ActionLink("Back to list", "Index", null, new { @class = "btn btn-light ml-2" })
            </div>
        }
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ArtStore.Web/Areas/Admin/Views/OrderManagement/GetOrderDetails.cshtml
@model IEnumerable<OrderDetail>
<br />
<br />
<center>
    <table class="table table-condensed">
        <tr class="d-flex center-title">
            <th class="col-md-2">Product</th>
            <th class="col-md-2">Quantity</th>
            <th class="col-md-2">Price</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr class="d-flex center-title">
                <td class="col-md-2">@Html.Action("GetArtName", "OrderManagement", new { artId = item.ArtId })</td>
                <td class="col-md-2">@item.Quantity</td>
                <td class="col-md-2">@item.Price</td>
            </tr>
        }
    </table>
</center>

ArtStore.Web/Areas/Admin/Views/OrderManagement/Index.cshtml
@model IEnumerable<ArtStore.Models.Order>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CreateDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AccountId)
        </th>
        
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CreateDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPrice)
        </td>
        <td>
            @(item.Status == 0 ? "Mới" : "Hoàn Thành")
        </td>
        <td>
            @Html.Action("GetAccountName", "OrderManagement", new { accId = item.AccountId })
        </td>
        <td style="text-align:end">
            <a href="@Url.Action("Edit","OrderManagement",new { id = item.Id })" style="color:cornflowerblue"><i class="fas fa-edit"></i></a>
            <a href="@Url.Action("Details","OrderManagement",new { id = item.Id })" style="color:cornflowerblue"><i class="fas fa-info-circle"></i></a>
            <a href="@Url.Action("Delete","OrderManagement",new { id = item.Id })" style="color:cornflowerblue"><i class="fas fa-backspace"></i></a>
        </td>
        
    </tr>
}

</table>