ArtStore.Web/Areas/Admin/Controllers/ArtManagementController.cs
using ArtStore.Models;
using ArtStore.Services;
using ArtStore.Web.Areas.Admin.ViewModels;
using System;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ArtStore.Web.Areas.Admin.Controllers
{
    public class ArtManagementController : Controller
    {
        private readonly IArtServices _artServices;
        private readonly ICategoryServices _categoryServices;

        public ArtManagementController(IArtServices artServices, ICategoryServices categoryServices)
        {
            _artServices = artServices;
            _categoryServices = categoryServices;
        }

        // GET: Admin/ArtManagement
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string search, int? pageIndex = 1, int pageSize = 10)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (search != null)
            {
                pageIndex = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewData["CurrentFilter"] = search;

            Expression<Func<Art, bool>> filter = null;

            if (!String.IsNullOrEmpty(search))
            {
                filter = c => c.Name.Contains(search);
            }

            Func<IQueryable<Art>, IOrderedQueryable<Art>> orderBy = null;

            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = n => n.OrderByDescending(c => c.Name);
                    break;
                default:
                    orderBy = n => n.OrderBy(p => p.Name);
                    break;
            }

            var arts = await _artServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(arts);
        }

        // GET: Admin/ArtManagement/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_categoryServices.GetAll(), "Id","Name");
            var artViewModel = new ArtViewModel();
            return View(artViewModel);
        }

        // POST: Admin/ArtManagement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(ArtViewModel artViewModel, HttpPostedFileBase uploadImage)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            ViewBag.ModelState = errors;
            if (ModelState.IsValid)
            {
                string fileName = "";
                if (uploadImage != null)
                {
                    fileName = Path.GetFileName(uploadImage.FileName);
                    string folderPath = Path.Combine(Server.MapPath("~/Assets/images"), uploadImage.FileName);
                    uploadImage.SaveAs(folderPath);
                }
                artViewModel.Image = fileName;
                var art = new Art
                {
                    Name = artViewModel.Name,
                    Image = artViewModel.Image,
                    Description = artViewModel.Description,
                    Price = artViewModel.Price,
                    SalePercent = artViewModel.SalePercent,
                    CategoryId = artViewModel.CategoryId
                };

                var result = _artServices.Add(art);
                if (result > 0)
                {
                    TempData["Message"] = "Tạo thành công.";
                }
                else
                {
                    TempData["Message"] = "Tạo thất bại. Thử lại sao nhé!";
                }
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(_categoryServices.GetAll(), "Id", "Name", artViewModel.CategoryId);
            return View(artViewModel);
        }

        // GET: Admin/ArtManagement/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Art art = _artServices.GetById((int)id);
            if (art == null)
            {
                return HttpNotFound();
            }

            var artViewModel = new ArtViewModel()
            {
                Id = art.Id,
                Name = art.Name,
                Description = art.Description,
                Image = art.Image,
                Price = art.Price,
                SalePercent = art.SalePercent,
                CategoryId = art.CategoryId
            };

            ViewBag.CategoryId = new SelectList(_categoryServices.GetAll(), "Id", "Name", artViewModel.CategoryId);
            return View(artViewModel);
        }

        // POST: Admin/ArtManagement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(ArtViewModel artViewModel)
        {
            if (ModelState.IsValid)
            {

                var art = _artServices.GetById(artViewModel.Id);
                if(art == null)
                {
                    return HttpNotFound();
                }

                art.Name = artViewModel.Name;
                art.Image = artViewModel.Image;
                art.Description = artViewModel.Description;
                art.Price = artViewModel.Price;
                art.SalePercent = artViewModel.SalePercent;
                art.CategoryId = artViewModel.CategoryId;

                var result = _artServices.Update(art);
                if (result)
                {
                    TempData["Message"] = "Cập nhật thành công.";
                }
                else
                {
                    TempData["Message"] = "Cập nhật thất bại.";
                }
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(_categoryServices.GetAll(), "Id", "Name", artViewModel.CategoryId);
            return View(artViewModel);
        }

        // POST: Admin/ArtManagement/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var result = _artServices.Delete(id);
            if (result)
            {
                TempData["Message"] = "Xóa thành công.";
            }
            else
            {
                TempData["Message"] = "Xóa thất bại.";
            }
            return RedirectToAction("Index");
        }
    }
}

ArtStore.Web/Areas/Identity/Controllers/UserAdminController.cs
using ArtStore.Models;
using ArtStore.Web.Areas.Identity.ViewModels;
using ArtStore.Web.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ArtStore.Web.Areas.Identity.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(AccountManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private AccountManager _userManager;
        public AccountManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext().GetUserManager<AccountManager>();
            private set => _userManager = value;
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get => _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            private set => _roleManager = value;
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index(string search)
        {
            if (!String.IsNullOrEmpty(search))
            {
                var user = await UserManager.FindByNameAsync(search);
            }
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new Account { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminResult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminResult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminResult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

ArtStore.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/AssetsAdmin/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/AssetsAdmin/css/sb-admin-2.min.css" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="~/AssetsAdmin/vendor/datatables/dataTables.bootstrap4.min.css" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body id="page-top">
    @if (Request.IsAuthenticated && User.IsInRole("Administrator"))
    {
        <div id="wrapper">
            <ul style="background:grey" class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

                <!-- Sidebar - Brand -->
                <a class="sidebar-brand d-flex align-items-center justify-content-center" href="@Url.Action("Index", "Home", new {area=""})">
                    <img style="width:30%" src="https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Dot_Art_logo.svg/1200px-Dot_Art_logo.svg.png" />
                </a>

                <!-- Divider -->
                <hr class="sidebar-divider my-0">




                <!-- Nav Item - Pages Collapse Menu -->
                <!-- Nav Item - Charts -->
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "UsersAdmin", new { area = "Identity" })">
                        <i class="fa fa-users"></i>
                        <span>User</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "RolesAdmin", new { area = "Identity" })">
                        <i class="fa fa-arrow-up"></i>
                        <span>Role</span>
                    </a>
                </li>
                <!-- Nav Item - Tables -->
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "ArtManagement", new { area = "Admin" })">
                        <i class="fa fa-palette"></i>
                        <span>Art</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "CategoryManagement", new { area = "Admin" })">
                        <i class="fa fa-tasks" aria-hidden="true"></i>
                        <span>Category</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "OrderManagement", new { area = "Admin" })">
                        <i class="fa fa-truck"></i>
                        <span>Order</span>
                    </a>
                </li>
                <!-- Divider -->
                <hr class="sidebar-divider d-none d-md-block">

                <!-- Sidebar Toggler (Sidebar) -->
                <div class="text-center d-none d-md-inline">
                    <button class="rounded-circle border-0" id="sidebarToggle"></button>
                </div>

            </ul>
            <div id="content-wrapper" class="d-flex flex-column">

                <!-- Main Content -->
                <div id="content">

                    <!-- Topbar -->
                    <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                        <!-- Sidebar Toggle (Topbar) -->
                        <form class="form-inline">
                            <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                                <i class="fa fa-bars"></i>
                            </button>
                        </form>

                        <!-- Topbar Search -->
                        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                            <div class="input-group">
                                <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                                       aria-label="Search" aria-describedby="basic-addon2" name="search">
                                <div class="input-group-append">
                                    <button class="btn btn-primary" type="submit">
                                        <i class="fas fa-search fa-sm"></i>
                                    </button>
                                </div>
                            </div>
                        </form>

                        <!-- Topbar Navbar -->
                        <ul class="navbar-nav ml-auto">

                            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                            <li class="nav-item dropdown no-arrow d-sm-none">
                                <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                   data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="fas fa-search fa-fw"></i>
                                </a>
                                <!-- Dropdown - Messages -->
                                <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                     aria-labelledby="searchDropdown">
                                    <form class="form-inline mr-auto w-100 navbar-search">
                                        <div class="input-group">
                                            <input type="text" class="form-control bg-light border-0 small"
                                                   placeholder="Search for..." aria-label="Search"
                                                   aria-describedby="basic-addon2">
                                            <div class="input-group-append">
                                                <button class="btn btn-primary" type="button">
                                                    <i class="fas fa-search fa-sm"></i>
                                                </button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </li>

                            <!-- Nav Item - Alerts -->
                            <li class="nav-item dropdown no-arrow mx-1">
                                @Html.Partial("_LoginPartial")
                                <!-- Dropdown - Alerts -->

                            </li>

                        </ul>

                    </nav>
                    <!-- End of Topbar -->
                    <!-- Begin Page Content -->
                    <div class="container-fluid">
                        <div class="card shadow mb-4">

                            <div class="card-body">
                                <div class="table-responsive">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.container-fluid -->

                </div>
                <!-- End of Main Content -->
            </div>
        </div>
    }







    <script src="~/AssetsAdmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/AssetsAdmin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/AssetsAdmin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/AssetsAdmin/vendor/datatables/jquery.dataTables.min.js"></script>
    <script src="~/AssetsAdmin/vendor/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/AssetsAdmin/js/demo/datatables-demo.js"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>